### ISSUE TITLE
Year Determination

### ISSUE THREAD

**Issue by brancengregory** [alekrutkowski/wiod.diagrammer#1]
Hello,

I'm having trouble figuring out how the year to be selected is decided. Any tips?

Thanks

**Comment by alekrutkowski** [comment]
The year is determined through an argument of the **`loadWIOD`** function -- the name of an .RData file. In the example, the latest year available (2014) is used: **`W <- loadWIOD('WIOT2014_October16_ROW.RData')`**.  The file **wiot_r_Nov16.zip** (to be downloaded from the WIOD website, [the link](http://www.wiod.org/protected3/data16/wiot_ROW/wiot_r_Nov16.zip) is in the example) contains the .RData files for the years 2000--2014.

**Comment by brancengregory** [comment]
Thanks for your response. That's what I was thinking, just wanted to make sure. Great work.
